@extends('layouts.app')
@section('title', 'Manage account · Instagram Automation')
@section('content')
<div class="mb-4"><a class="small text-decoration-none" href="{{ route('accounts.index') }}">← Back to accounts</a><div class="eyebrow mt-3 mb-2">Advanced account settings</div><h1 class="page-title h2 mb-2">{{ $item->exists ? 'Manage Instagram account' : 'Add account manually' }}</h1><p class="page-subtitle mb-0">OAuth is the recommended connection method. This form changes account metadata only.</p></div>
<div class="alert alert-warning border-0"><strong>Manual setup does not generate an access token.</strong><div class="small mt-1">Use “Connect with Meta” on the Accounts page for a working connection. Existing OAuth tokens are encrypted and never displayed here.</div></div>
<form class="card" method="post" action="{{ $item->exists?route('accounts.update',$item):route('accounts.store') }}">@csrf @if($item->exists)@method('PUT')@endif
    <div class="card-body p-4"><div class="row g-3">
        <div class="col-md-6"><label class="form-label fw-semibold" for="account-label">Account label</label><input id="account-label" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$item->name) }}" placeholder="Example: Umair Digital" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="account-username">Instagram username</label><div class="input-group"><span class="input-group-text">@</span><input id="account-username" class="form-control" name="username" value="{{ old('username',$item->username) }}" placeholder="username"></div></div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="instagram-user-id">Instagram user ID</label><input id="instagram-user-id" class="form-control @error('instagram_user_id') is-invalid @enderror" name="instagram_user_id" value="{{ old('instagram_user_id',$item->instagram_user_id) }}" required><div class="form-text">The numeric ID returned by the Graph API.</div>@error('instagram_user_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="facebook-page-id">Facebook Page ID</label><input id="facebook-page-id" class="form-control" name="facebook_page_id" value="{{ old('facebook_page_id',$item->facebook_page_id) }}"><div class="form-text">Required only for the Facebook Login and connected Page flow.</div></div>
    </div><div class="form-check form-switch mt-4"><input class="form-check-input" type="checkbox" role="switch" id="account-active" name="is_active" value="1" @checked(old('is_active',$item->is_active??true))><label class="form-check-label fw-semibold" for="account-active">Allow this account to run automations</label></div></div>
    <div class="card-footer bg-white d-flex flex-column-reverse flex-sm-row justify-content-end gap-2 p-3"><a class="btn btn-outline-secondary" href="{{ route('accounts.index') }}">Cancel</a><button class="btn btn-primary">Save account</button></div>
</form>
@endsection
