@extends('layouts.app')
@section('title', ($item->exists ? 'Edit' : 'New').' resource · Instagram Automation')
@section('content')
<div class="mb-4"><a class="small text-decoration-none" href="{{ route('resources.index') }}">← Back to media and links</a><div class="eyebrow mt-3 mb-2">Content library</div><h1 class="page-title h2 mb-2">{{ $item->exists ? 'Edit resource' : 'Add resource' }}</h1><p class="page-subtitle mb-0">Use a media item to target one Reel or post. Use a link resource inside message templates.</p></div>
<form class="card" method="post" action="{{ $item->exists?route('resources.update',$item):route('resources.store') }}">@csrf @if($item->exists)@method('PUT')@endif
    <div class="card-body p-4"><div class="row g-3">
        <div class="col-md-6"><label class="form-label fw-semibold" for="resource-name">Name</label><input id="resource-name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$item->name) }}" placeholder="Example: Manali Reel" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="resource-type">Type</label><select id="resource-type" class="form-select" name="type"><option value="media" @selected(old('type',$item->type ?: 'media')==='media')>Instagram Reel or post</option><option value="link" @selected(old('type',$item->type)==='link')>Destination link</option></select></div>
        <div class="col-md-6 media-input"><label class="form-label fw-semibold" for="media-id">Instagram media ID</label><input id="media-id" class="form-control" name="instagram_media_id" value="{{ old('instagram_media_id',$item->instagram_media_id) }}" placeholder="18019326794001472"><div class="form-text">Use the numeric Graph API media ID, not the shortcode or username.</div></div>
        <div class="col-md-6 media-input"><label class="form-label fw-semibold" for="permalink">Instagram permalink</label><input id="permalink" type="url" class="form-control @error('permalink') is-invalid @enderror" name="permalink" value="{{ old('permalink',$item->permalink) }}" placeholder="https://www.instagram.com/reel/..."><div class="form-text">Used for reference in the dashboard.</div>@error('permalink')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 link-input"><label class="form-label fw-semibold" for="destination-url">Destination URL</label><input id="destination-url" type="url" class="form-control @error('destination_url') is-invalid @enderror" name="destination_url" value="{{ old('destination_url',$item->destination_url) }}" placeholder="https://example.com/offer"><div class="form-text">This replaces <code>{resource_url}</code> in the selected template.</div>@error('destination_url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div><div class="form-check form-switch mt-4"><input class="form-check-input" type="checkbox" role="switch" id="resource-active" name="is_active" value="1" @checked(old('is_active',$item->is_active??true))><label class="form-check-label fw-semibold" for="resource-active">Available to automation rules</label></div></div>
    <div class="card-footer bg-white d-flex flex-column-reverse flex-sm-row justify-content-end gap-2 p-3"><a class="btn btn-outline-secondary" href="{{ route('resources.index') }}">Cancel</a><button class="btn btn-primary">Save resource</button></div>
</form>
@endsection
@push('scripts')<script>(()=>{const type=document.getElementById('resource-type');const render=()=>{document.querySelectorAll('.media-input').forEach(el=>el.classList.toggle('d-none',type.value!=='media'));document.querySelectorAll('.link-input').forEach(el=>el.classList.toggle('d-none',type.value!=='link'));};type.addEventListener('change',render);render();})();</script>@endpush
