@extends('layouts.app')
@section('title', ($item->exists ? 'Edit' : 'New').' template · Instagram Automation')
@section('content')
<div class="mb-4"><a class="small text-decoration-none" href="{{ route('templates.index') }}">← Back to templates</a><div class="eyebrow mt-3 mb-2">Message content</div><h1 class="page-title h2 mb-2">{{ $item->exists ? 'Edit template' : 'Create template' }}</h1><p class="page-subtitle mb-0">Write the private message that a matching automation will queue for delivery.</p></div>
<form class="card" method="post" action="{{ $item->exists?route('templates.update',$item):route('templates.store') }}">@csrf @if($item->exists)@method('PUT')@endif
    <div class="card-body p-4"><label class="form-label fw-semibold" for="template-name">Template name</label><input id="template-name" class="form-control mb-3 @error('name') is-invalid @enderror" name="name" value="{{ old('name',$item->name) }}" placeholder="Example: Send location details" required>@error('name')<div class="invalid-feedback mb-3">{{ $message }}</div>@enderror
    <label class="form-label fw-semibold" for="template-body">Message</label><textarea id="template-body" class="form-control @error('body') is-invalid @enderror" rows="7" name="body" placeholder="Hi {first_name}, here are the details: {resource_url}" required>{{ old('body',$item->body) }}</textarea>@error('body')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">Available variables: <code>{first_name}</code> and <code>{resource_url}</code>.</div>
    <div class="activity-detail mt-4"><div class="small fw-semibold mb-2">Preview</div><div id="message-preview" class="code-break"></div></div>
    <div class="form-check form-switch mt-4"><input class="form-check-input" type="checkbox" role="switch" id="template-active" name="is_active" value="1" @checked(old('is_active',$item->is_active??true))><label class="form-check-label fw-semibold" for="template-active">Available to automation rules</label></div></div>
    <div class="card-footer bg-white d-flex flex-column-reverse flex-sm-row justify-content-end gap-2 p-3"><a class="btn btn-outline-secondary" href="{{ route('templates.index') }}">Cancel</a><button class="btn btn-primary">Save template</button></div>
</form>
@endsection
@push('scripts')<script>(()=>{const input=document.getElementById('template-body');const output=document.getElementById('message-preview');const render=()=>output.textContent=(input.value||'Your message preview will appear here.').replaceAll('{first_name}','Alex').replaceAll('{resource_url}','https://example.com/resource');input.addEventListener('input',render);render();})();</script>@endpush
