@extends('layouts.app')
@section('title', 'Templates · Instagram Automation')
@section('content')
<div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-end gap-3 mb-4"><div><div class="eyebrow mb-2">Reusable content</div><h1 class="page-title h2 mb-2">Message templates</h1><p class="page-subtitle mb-0">Prepare consistent private messages and preview variables before using them in rules.</p></div><a class="btn btn-primary" href="{{ route('templates.create') }}">Create template</a></div>
<div class="card border-primary-subtle bg-primary-subtle mb-4"><div class="card-body p-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h2 class="h5 mb-2">Starter examples</h2><p class="small text-muted mb-0">Copy a paused example, edit it for your business, and activate it only when it is ready.</p></div><a class="btn btn-sm btn-outline-primary align-self-start" href="{{ route('setup.index') }}">View setup guide</a></div><div class="row g-3 mt-1">@foreach($examples as $example)<div class="col-md-6"><div class="bg-white rounded-3 border p-3 h-100"><div class="fw-semibold">{{ $example['name'] }}</div><p class="small text-muted mt-2 mb-2">{{ $example['description'] }}</p><div class="small code-break mb-3">{{ $example['body'] }}</div><form method="post" action="{{ route('templates.examples.duplicate', $example['key']) }}">@csrf<button class="btn btn-sm btn-outline-primary">Use this example</button></form></div></div>@endforeach</div></div></div>
<div class="row g-3">
@forelse($items as $item)
    <div class="col-md-6"><a class="card list-card h-100 text-decoration-none text-reset" href="{{ route('templates.edit',$item) }}"><div class="card-body"><div class="d-flex align-items-start justify-content-between gap-2 mb-3"><div class="icon-tile">T</div><span class="badge-status {{ $item->is_active ? 'status-ready' : 'status-neutral' }}">{{ $item->is_active ? 'Active' : 'Paused' }}</span></div><h2 class="h5 mb-2">{{ $item->name }}</h2><p class="text-muted mb-0 code-break">{{ \Illuminate\Support\Str::limit($item->body, 180) }}</p></div></a></div>
@empty
    <div class="col-12"><div class="card"><div class="empty-state"><div class="icon-tile mx-auto mb-3">T</div><strong>No message templates yet</strong><div class="mt-1 mb-2">A template is the private message sent after a rule matches. Start with a starter example above or create your own.</div><div class="small mb-3"><code>{first_name}</code> personalizes the contact name and <code>{resource_url}</code> inserts a link resource.</div><a class="btn btn-primary" href="{{ route('templates.create') }}">Create template</a></div></div></div>
@endforelse
</div><div class="mt-4">{{ $items->links() }}</div>
@endsection
